// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.Bareme;
import nc.mairie.siale.domain.BaremeDataOnDemand;
import nc.mairie.siale.domain.BaremeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaremeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BaremeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BaremeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BaremeIntegrationTest: @Transactional;
    
    @Autowired
    private BaremeDataOnDemand BaremeIntegrationTest.dod;
    
    @Test
    public void BaremeIntegrationTest.testCountBaremes() {
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", dod.getRandomBareme());
        long count = Bareme.countBaremes();
        Assert.assertTrue("Counter for 'Bareme' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BaremeIntegrationTest.testFindBareme() {
        Bareme obj = dod.getRandomBareme();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to provide an identifier", id);
        obj = Bareme.findBareme(id);
        Assert.assertNotNull("Find method for 'Bareme' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bareme' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BaremeIntegrationTest.testFindAllBaremes() {
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", dod.getRandomBareme());
        long count = Bareme.countBaremes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bareme', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bareme> result = Bareme.findAllBaremes();
        Assert.assertNotNull("Find all method for 'Bareme' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bareme' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BaremeIntegrationTest.testFindBaremeEntries() {
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", dod.getRandomBareme());
        long count = Bareme.countBaremes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bareme> result = Bareme.findBaremeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bareme' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bareme' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BaremeIntegrationTest.testFlush() {
        Bareme obj = dod.getRandomBareme();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to provide an identifier", id);
        obj = Bareme.findBareme(id);
        Assert.assertNotNull("Find method for 'Bareme' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBareme(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bareme' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BaremeIntegrationTest.testMergeUpdate() {
        Bareme obj = dod.getRandomBareme();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to provide an identifier", id);
        obj = Bareme.findBareme(id);
        boolean modified =  dod.modifyBareme(obj);
        Integer currentVersion = obj.getVersion();
        Bareme merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bareme' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BaremeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", dod.getRandomBareme());
        Bareme obj = dod.getNewTransientBareme(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bareme' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bareme' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Bareme' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BaremeIntegrationTest.testRemove() {
        Bareme obj = dod.getRandomBareme();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bareme' failed to provide an identifier", id);
        obj = Bareme.findBareme(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bareme' with identifier '" + id + "'", Bareme.findBareme(id));
    }
    
}
