// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.Bareme;
import nc.mairie.siale.domain.BaremeDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect BaremeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BaremeDataOnDemand: @Component;
    
    private Random BaremeDataOnDemand.rnd = new SecureRandom();
    
    private List<Bareme> BaremeDataOnDemand.data;
    
    public Bareme BaremeDataOnDemand.getNewTransientBareme(int index) {
        Bareme obj = new Bareme();
        setDateCreation(obj, index);
        setNom(obj, index);
        return obj;
    }
    
    public void BaremeDataOnDemand.setDateCreation(Bareme obj, int index) {
        Date dateCreation = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreation(dateCreation);
    }
    
    public void BaremeDataOnDemand.setNom(Bareme obj, int index) {
        String nom = "nom_" + index;
        obj.setNom(nom);
    }
    
    public Bareme BaremeDataOnDemand.getSpecificBareme(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Bareme obj = data.get(index);
        Long id = obj.getId();
        return Bareme.findBareme(id);
    }
    
    public Bareme BaremeDataOnDemand.getRandomBareme() {
        init();
        Bareme obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Bareme.findBareme(id);
    }
    
    public boolean BaremeDataOnDemand.modifyBareme(Bareme obj) {
        return false;
    }
    
    public void BaremeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Bareme.findBaremeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Bareme' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Bareme>();
        for (int i = 0; i < 10; i++) {
            Bareme obj = getNewTransientBareme(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
