// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.ControleurSIALE;
import nc.mairie.siale.domain.ControleurSIALEDataOnDemand;
import nc.mairie.siale.domain.ControleurSIALEIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ControleurSIALEIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ControleurSIALEIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ControleurSIALEIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ControleurSIALEIntegrationTest: @Transactional;
    
    @Autowired
    private ControleurSIALEDataOnDemand ControleurSIALEIntegrationTest.dod;
    
    @Test
    public void ControleurSIALEIntegrationTest.testCountControleurSIALEs() {
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", dod.getRandomControleurSIALE());
        long count = ControleurSIALE.countControleurSIALEs();
        Assert.assertTrue("Counter for 'ControleurSIALE' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testFindControleurSIALE() {
        ControleurSIALE obj = dod.getRandomControleurSIALE();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to provide an identifier", id);
        obj = ControleurSIALE.findControleurSIALE(id);
        Assert.assertNotNull("Find method for 'ControleurSIALE' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ControleurSIALE' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testFindAllControleurSIALEs() {
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", dod.getRandomControleurSIALE());
        long count = ControleurSIALE.countControleurSIALEs();
        Assert.assertTrue("Too expensive to perform a find all test for 'ControleurSIALE', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ControleurSIALE> result = ControleurSIALE.findAllControleurSIALEs();
        Assert.assertNotNull("Find all method for 'ControleurSIALE' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ControleurSIALE' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testFindControleurSIALEEntries() {
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", dod.getRandomControleurSIALE());
        long count = ControleurSIALE.countControleurSIALEs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ControleurSIALE> result = ControleurSIALE.findControleurSIALEEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ControleurSIALE' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ControleurSIALE' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testFlush() {
        ControleurSIALE obj = dod.getRandomControleurSIALE();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to provide an identifier", id);
        obj = ControleurSIALE.findControleurSIALE(id);
        Assert.assertNotNull("Find method for 'ControleurSIALE' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyControleurSIALE(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ControleurSIALE' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testMergeUpdate() {
        ControleurSIALE obj = dod.getRandomControleurSIALE();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to provide an identifier", id);
        obj = ControleurSIALE.findControleurSIALE(id);
        boolean modified =  dod.modifyControleurSIALE(obj);
        Integer currentVersion = obj.getVersion();
        ControleurSIALE merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ControleurSIALE' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", dod.getRandomControleurSIALE());
        ControleurSIALE obj = dod.getNewTransientControleurSIALE(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ControleurSIALE' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ControleurSIALE' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ControleurSIALEIntegrationTest.testRemove() {
        ControleurSIALE obj = dod.getRandomControleurSIALE();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ControleurSIALE' failed to provide an identifier", id);
        obj = ControleurSIALE.findControleurSIALE(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ControleurSIALE' with identifier '" + id + "'", ControleurSIALE.findControleurSIALE(id));
    }
    
}
