// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.Droit;
import nc.mairie.siale.domain.DroitDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect DroitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DroitDataOnDemand: @Component;
    
    private Random DroitDataOnDemand.rnd = new SecureRandom();
    
    private List<Droit> DroitDataOnDemand.data;
    
    public Droit DroitDataOnDemand.getNewTransientDroit(int index) {
        Droit obj = new Droit();
        setNom(obj, index);
        return obj;
    }
    
    public void DroitDataOnDemand.setNom(Droit obj, int index) {
        String nom = "nom_" + index;
        obj.setNom(nom);
    }
    
    public Droit DroitDataOnDemand.getSpecificDroit(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Droit obj = data.get(index);
        Long id = obj.getId();
        return Droit.findDroit(id);
    }
    
    public Droit DroitDataOnDemand.getRandomDroit() {
        init();
        Droit obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Droit.findDroit(id);
    }
    
    public boolean DroitDataOnDemand.modifyDroit(Droit obj) {
        return false;
    }
    
    public void DroitDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Droit.findDroitEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Droit' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Droit>();
        for (int i = 0; i < 10; i++) {
            Droit obj = getNewTransientDroit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
