// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.Etablissement;
import nc.mairie.siale.domain.EtablissementDataOnDemand;
import nc.mairie.siale.domain.EtablissementIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EtablissementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EtablissementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EtablissementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EtablissementIntegrationTest: @Transactional;
    
    @Autowired
    private EtablissementDataOnDemand EtablissementIntegrationTest.dod;
    
    @Test
    public void EtablissementIntegrationTest.testCountEtablissements() {
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", dod.getRandomEtablissement());
        long count = Etablissement.countEtablissements();
        Assert.assertTrue("Counter for 'Etablissement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EtablissementIntegrationTest.testFindEtablissement() {
        Etablissement obj = dod.getRandomEtablissement();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to provide an identifier", id);
        obj = Etablissement.findEtablissement(id);
        Assert.assertNotNull("Find method for 'Etablissement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Etablissement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EtablissementIntegrationTest.testFindAllEtablissements() {
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", dod.getRandomEtablissement());
        long count = Etablissement.countEtablissements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Etablissement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Etablissement> result = Etablissement.findAllEtablissements();
        Assert.assertNotNull("Find all method for 'Etablissement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Etablissement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EtablissementIntegrationTest.testFindEtablissementEntries() {
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", dod.getRandomEtablissement());
        long count = Etablissement.countEtablissements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Etablissement> result = Etablissement.findEtablissementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Etablissement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Etablissement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EtablissementIntegrationTest.testFlush() {
        Etablissement obj = dod.getRandomEtablissement();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to provide an identifier", id);
        obj = Etablissement.findEtablissement(id);
        Assert.assertNotNull("Find method for 'Etablissement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEtablissement(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Etablissement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EtablissementIntegrationTest.testMergeUpdate() {
        Etablissement obj = dod.getRandomEtablissement();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to provide an identifier", id);
        obj = Etablissement.findEtablissement(id);
        boolean modified =  dod.modifyEtablissement(obj);
        Integer currentVersion = obj.getVersion();
        Etablissement merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Etablissement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EtablissementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", dod.getRandomEtablissement());
        Etablissement obj = dod.getNewTransientEtablissement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Etablissement' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Etablissement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EtablissementIntegrationTest.testRemove() {
        Etablissement obj = dod.getRandomEtablissement();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Etablissement' failed to provide an identifier", id);
        obj = Etablissement.findEtablissement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Etablissement' with identifier '" + id + "'", Etablissement.findEtablissement(id));
    }
    
}
