// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import nc.mairie.siale.domain.MissionDocumentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MissionDocumentIntegrationTest_Roo_Configurable {
    
    declare @type: MissionDocumentIntegrationTest: @Configurable;
    
}
