// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.MissionAction;
import nc.mairie.siale.domain.MissionActionDataOnDemand;
import nc.mairie.siale.domain.MissionActionIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MissionActionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MissionActionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MissionActionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MissionActionIntegrationTest: @Transactional;
    
    @Autowired
    private MissionActionDataOnDemand MissionActionIntegrationTest.dod;
    
    @Test
    public void MissionActionIntegrationTest.testCountMissionActions() {
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", dod.getRandomMissionAction());
        long count = MissionAction.countMissionActions();
        Assert.assertTrue("Counter for 'MissionAction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MissionActionIntegrationTest.testFindMissionAction() {
        MissionAction obj = dod.getRandomMissionAction();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to provide an identifier", id);
        obj = MissionAction.findMissionAction(id);
        Assert.assertNotNull("Find method for 'MissionAction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MissionAction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MissionActionIntegrationTest.testFindAllMissionActions() {
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", dod.getRandomMissionAction());
        long count = MissionAction.countMissionActions();
        Assert.assertTrue("Too expensive to perform a find all test for 'MissionAction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MissionAction> result = MissionAction.findAllMissionActions();
        Assert.assertNotNull("Find all method for 'MissionAction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MissionAction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MissionActionIntegrationTest.testFindMissionActionEntries() {
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", dod.getRandomMissionAction());
        long count = MissionAction.countMissionActions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MissionAction> result = MissionAction.findMissionActionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MissionAction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MissionAction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MissionActionIntegrationTest.testFlush() {
        MissionAction obj = dod.getRandomMissionAction();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to provide an identifier", id);
        obj = MissionAction.findMissionAction(id);
        Assert.assertNotNull("Find method for 'MissionAction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMissionAction(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MissionAction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionActionIntegrationTest.testMergeUpdate() {
        MissionAction obj = dod.getRandomMissionAction();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to provide an identifier", id);
        obj = MissionAction.findMissionAction(id);
        boolean modified =  dod.modifyMissionAction(obj);
        Integer currentVersion = obj.getVersion();
        MissionAction merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MissionAction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionActionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", dod.getRandomMissionAction());
        MissionAction obj = dod.getNewTransientMissionAction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MissionAction' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MissionAction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MissionActionIntegrationTest.testRemove() {
        MissionAction obj = dod.getRandomMissionAction();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionAction' failed to provide an identifier", id);
        obj = MissionAction.findMissionAction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MissionAction' with identifier '" + id + "'", MissionAction.findMissionAction(id));
    }
    
}
