// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.Mission;
import nc.mairie.siale.domain.MissionActivite;
import nc.mairie.siale.domain.MissionActiviteDataOnDemand;
import nc.mairie.siale.domain.MissionDataOnDemand;
import nc.mairie.siale.domain.Param;
import nc.mairie.siale.domain.ParamDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MissionActiviteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MissionActiviteDataOnDemand: @Component;
    
    private Random MissionActiviteDataOnDemand.rnd = new SecureRandom();
    
    private List<MissionActivite> MissionActiviteDataOnDemand.data;
    
    @Autowired
    private ParamDataOnDemand MissionActiviteDataOnDemand.paramDataOnDemand;
    
    @Autowired
    private MissionDataOnDemand MissionActiviteDataOnDemand.missionDataOnDemand;
    
    public MissionActivite MissionActiviteDataOnDemand.getNewTransientMissionActivite(int index) {
        MissionActivite obj = new MissionActivite();
        setPrincipale(obj, index);
        setTheActivite(obj, index);
        setTheMission(obj, index);
        return obj;
    }
    
    public void MissionActiviteDataOnDemand.setPrincipale(MissionActivite obj, int index) {
        Boolean principale = Boolean.TRUE;
        obj.setPrincipale(principale);
    }
    
    public void MissionActiviteDataOnDemand.setTheActivite(MissionActivite obj, int index) {
        Param theActivite = paramDataOnDemand.getRandomParam();
        obj.setTheActivite(theActivite);
    }
    
    public void MissionActiviteDataOnDemand.setTheMission(MissionActivite obj, int index) {
        Mission theMission = missionDataOnDemand.getRandomMission();
        obj.setTheMission(theMission);
    }
    
    public MissionActivite MissionActiviteDataOnDemand.getSpecificMissionActivite(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MissionActivite obj = data.get(index);
        Long id = obj.getId();
        return MissionActivite.findMissionActivite(id);
    }
    
    public MissionActivite MissionActiviteDataOnDemand.getRandomMissionActivite() {
        init();
        MissionActivite obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MissionActivite.findMissionActivite(id);
    }
    
    public boolean MissionActiviteDataOnDemand.modifyMissionActivite(MissionActivite obj) {
        return false;
    }
    
    public void MissionActiviteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MissionActivite.findMissionActiviteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MissionActivite' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MissionActivite>();
        for (int i = 0; i < 10; i++) {
            MissionActivite obj = getNewTransientMissionActivite(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
