// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.MissionDocument;
import nc.mairie.siale.domain.MissionDocumentDataOnDemand;
import nc.mairie.siale.domain.MissionDocumentIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MissionDocumentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MissionDocumentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MissionDocumentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MissionDocumentIntegrationTest: @Transactional;
    
    @Autowired
    private MissionDocumentDataOnDemand MissionDocumentIntegrationTest.dod;
    
    @Test
    public void MissionDocumentIntegrationTest.testCountMissionDocuments() {
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", dod.getRandomMissionDocument());
        long count = MissionDocument.countMissionDocuments();
        Assert.assertTrue("Counter for 'MissionDocument' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testFindMissionDocument() {
        MissionDocument obj = dod.getRandomMissionDocument();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to provide an identifier", id);
        obj = MissionDocument.findMissionDocument(id);
        Assert.assertNotNull("Find method for 'MissionDocument' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MissionDocument' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testFindAllMissionDocuments() {
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", dod.getRandomMissionDocument());
        long count = MissionDocument.countMissionDocuments();
        Assert.assertTrue("Too expensive to perform a find all test for 'MissionDocument', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MissionDocument> result = MissionDocument.findAllMissionDocuments();
        Assert.assertNotNull("Find all method for 'MissionDocument' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MissionDocument' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testFindMissionDocumentEntries() {
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", dod.getRandomMissionDocument());
        long count = MissionDocument.countMissionDocuments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MissionDocument> result = MissionDocument.findMissionDocumentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MissionDocument' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MissionDocument' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testFlush() {
        MissionDocument obj = dod.getRandomMissionDocument();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to provide an identifier", id);
        obj = MissionDocument.findMissionDocument(id);
        Assert.assertNotNull("Find method for 'MissionDocument' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMissionDocument(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MissionDocument' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testMergeUpdate() {
        MissionDocument obj = dod.getRandomMissionDocument();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to provide an identifier", id);
        obj = MissionDocument.findMissionDocument(id);
        boolean modified =  dod.modifyMissionDocument(obj);
        Integer currentVersion = obj.getVersion();
        MissionDocument merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MissionDocument' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", dod.getRandomMissionDocument());
        MissionDocument obj = dod.getNewTransientMissionDocument(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MissionDocument' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MissionDocument' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MissionDocumentIntegrationTest.testRemove() {
        MissionDocument obj = dod.getRandomMissionDocument();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MissionDocument' failed to provide an identifier", id);
        obj = MissionDocument.findMissionDocument(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MissionDocument' with identifier '" + id + "'", MissionDocument.findMissionDocument(id));
    }
    
}
