// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.MissionDataOnDemand;
import nc.mairie.siale.domain.MissionDocument;
import nc.mairie.siale.domain.MissionDocumentDataOnDemand;
import nc.mairie.siale.domain.ParamDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MissionDocumentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MissionDocumentDataOnDemand: @Component;
    
    private Random MissionDocumentDataOnDemand.rnd = new SecureRandom();
    
    private List<MissionDocument> MissionDocumentDataOnDemand.data;
    
    @Autowired
    private ParamDataOnDemand MissionDocumentDataOnDemand.paramDataOnDemand;
    
    @Autowired
    private MissionDataOnDemand MissionDocumentDataOnDemand.missionDataOnDemand;
    
    public MissionDocument MissionDocumentDataOnDemand.getNewTransientMissionDocument(int index) {
        MissionDocument obj = new MissionDocument();
        setDateDocument(obj, index);
        return obj;
    }
    
    public void MissionDocumentDataOnDemand.setDateDocument(MissionDocument obj, int index) {
        Date dateDocument = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateDocument(dateDocument);
    }
    
    public MissionDocument MissionDocumentDataOnDemand.getSpecificMissionDocument(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MissionDocument obj = data.get(index);
        Long id = obj.getId();
        return MissionDocument.findMissionDocument(id);
    }
    
    public MissionDocument MissionDocumentDataOnDemand.getRandomMissionDocument() {
        init();
        MissionDocument obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MissionDocument.findMissionDocument(id);
    }
    
    public boolean MissionDocumentDataOnDemand.modifyMissionDocument(MissionDocument obj) {
        return false;
    }
    
    public void MissionDocumentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MissionDocument.findMissionDocumentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MissionDocument' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MissionDocument>();
        for (int i = 0; i < 10; i++) {
            MissionDocument obj = getNewTransientMissionDocument(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
