// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.MissionAction;
import nc.mairie.siale.domain.MissionActionDataOnDemand;
import nc.mairie.siale.domain.Param;
import nc.mairie.siale.domain.ParamDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MissionActionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MissionActionDataOnDemand: @Component;
    
    private Random MissionActionDataOnDemand.rnd = new SecureRandom();
    
    private List<MissionAction> MissionActionDataOnDemand.data;
    
    @Autowired
    private ParamDataOnDemand MissionActionDataOnDemand.paramDataOnDemand;
    
    public MissionAction MissionActionDataOnDemand.getNewTransientMissionAction(int index) {
        MissionAction obj = new MissionAction();
        setDateAction(obj, index);
        setTheAction(obj, index);
        return obj;
    }
    
    public void MissionActionDataOnDemand.setDateAction(MissionAction obj, int index) {
        Date dateAction = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateAction(dateAction);
    }
    
    public void MissionActionDataOnDemand.setTheAction(MissionAction obj, int index) {
        Param theAction = paramDataOnDemand.getRandomParam();
        obj.setTheAction(theAction);
    }
    
    public MissionAction MissionActionDataOnDemand.getSpecificMissionAction(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MissionAction obj = data.get(index);
        Long id = obj.getId();
        return MissionAction.findMissionAction(id);
    }
    
    public MissionAction MissionActionDataOnDemand.getRandomMissionAction() {
        init();
        MissionAction obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MissionAction.findMissionAction(id);
    }
    
    public boolean MissionActionDataOnDemand.modifyMissionAction(MissionAction obj) {
        return false;
    }
    
    public void MissionActionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MissionAction.findMissionActionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MissionAction' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MissionAction>();
        for (int i = 0; i < 10; i++) {
            MissionAction obj = getNewTransientMissionAction(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
