// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.Mission;
import nc.mairie.siale.domain.MissionDataOnDemand;
import nc.mairie.siale.domain.MissionIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MissionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MissionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MissionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MissionIntegrationTest: @Transactional;
    
    @Autowired
    private MissionDataOnDemand MissionIntegrationTest.dod;
    
    @Test
    public void MissionIntegrationTest.testCountMissions() {
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", dod.getRandomMission());
        long count = Mission.countMissions();
        Assert.assertTrue("Counter for 'Mission' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MissionIntegrationTest.testFindMission() {
        Mission obj = dod.getRandomMission();
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mission' failed to provide an identifier", id);
        obj = Mission.findMission(id);
        Assert.assertNotNull("Find method for 'Mission' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mission' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MissionIntegrationTest.testFindAllMissions() {
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", dod.getRandomMission());
        long count = Mission.countMissions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mission', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mission> result = Mission.findAllMissions();
        Assert.assertNotNull("Find all method for 'Mission' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mission' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MissionIntegrationTest.testFindMissionEntries() {
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", dod.getRandomMission());
        long count = Mission.countMissions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mission> result = Mission.findMissionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mission' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mission' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MissionIntegrationTest.testFlush() {
        Mission obj = dod.getRandomMission();
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mission' failed to provide an identifier", id);
        obj = Mission.findMission(id);
        Assert.assertNotNull("Find method for 'Mission' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMission(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mission' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionIntegrationTest.testMergeUpdate() {
        Mission obj = dod.getRandomMission();
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mission' failed to provide an identifier", id);
        obj = Mission.findMission(id);
        boolean modified =  dod.modifyMission(obj);
        Integer currentVersion = obj.getVersion();
        Mission merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mission' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MissionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", dod.getRandomMission());
        Mission obj = dod.getNewTransientMission(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mission' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mission' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Mission' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MissionIntegrationTest.testRemove() {
        Mission obj = dod.getRandomMission();
        Assert.assertNotNull("Data on demand for 'Mission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mission' failed to provide an identifier", id);
        obj = Mission.findMission(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mission' with identifier '" + id + "'", Mission.findMission(id));
    }
    
}
