// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.Notation;
import nc.mairie.siale.domain.NotationDataOnDemand;
import nc.mairie.siale.domain.NotationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NotationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NotationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NotationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NotationIntegrationTest: @Transactional;
    
    @Autowired
    private NotationDataOnDemand NotationIntegrationTest.dod;
    
    @Test
    public void NotationIntegrationTest.testCountNotations() {
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", dod.getRandomNotation());
        long count = Notation.countNotations();
        Assert.assertTrue("Counter for 'Notation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NotationIntegrationTest.testFindNotation() {
        Notation obj = dod.getRandomNotation();
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notation' failed to provide an identifier", id);
        obj = Notation.findNotation(id);
        Assert.assertNotNull("Find method for 'Notation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Notation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NotationIntegrationTest.testFindAllNotations() {
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", dod.getRandomNotation());
        long count = Notation.countNotations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Notation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Notation> result = Notation.findAllNotations();
        Assert.assertNotNull("Find all method for 'Notation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Notation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NotationIntegrationTest.testFindNotationEntries() {
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", dod.getRandomNotation());
        long count = Notation.countNotations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Notation> result = Notation.findNotationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Notation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Notation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NotationIntegrationTest.testFlush() {
        Notation obj = dod.getRandomNotation();
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notation' failed to provide an identifier", id);
        obj = Notation.findNotation(id);
        Assert.assertNotNull("Find method for 'Notation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNotation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Notation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotationIntegrationTest.testMergeUpdate() {
        Notation obj = dod.getRandomNotation();
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notation' failed to provide an identifier", id);
        obj = Notation.findNotation(id);
        boolean modified =  dod.modifyNotation(obj);
        Integer currentVersion = obj.getVersion();
        Notation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Notation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", dod.getRandomNotation());
        Notation obj = dod.getNewTransientNotation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Notation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Notation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Notation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NotationIntegrationTest.testRemove() {
        Notation obj = dod.getRandomNotation();
        Assert.assertNotNull("Data on demand for 'Notation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notation' failed to provide an identifier", id);
        obj = Notation.findNotation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Notation' with identifier '" + id + "'", Notation.findNotation(id));
    }
    
}
