// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.MissionDataOnDemand;
import nc.mairie.siale.domain.Notation;
import nc.mairie.siale.domain.NotationDataOnDemand;
import nc.mairie.siale.domain.NoteCritereDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NotationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NotationDataOnDemand: @Component;
    
    private Random NotationDataOnDemand.rnd = new SecureRandom();
    
    private List<Notation> NotationDataOnDemand.data;
    
    @Autowired
    private MissionDataOnDemand NotationDataOnDemand.missionDataOnDemand;
    
    @Autowired
    private NoteCritereDataOnDemand NotationDataOnDemand.noteCritereDataOnDemand;
    
    public Notation NotationDataOnDemand.getNewTransientNotation(int index) {
        Notation obj = new Notation();
        setNote(obj, index);
        return obj;
    }
    
    public void NotationDataOnDemand.setNote(Notation obj, int index) {
        double note = new Integer(index).doubleValue();
        obj.setNote(note);
    }
    
    public Notation NotationDataOnDemand.getSpecificNotation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Notation obj = data.get(index);
        Long id = obj.getId();
        return Notation.findNotation(id);
    }
    
    public Notation NotationDataOnDemand.getRandomNotation() {
        init();
        Notation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Notation.findNotation(id);
    }
    
    public boolean NotationDataOnDemand.modifyNotation(Notation obj) {
        return false;
    }
    
    public void NotationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Notation.findNotationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Notation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Notation>();
        for (int i = 0; i < 10; i++) {
            Notation obj = getNewTransientNotation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
