// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.NoteCritere;
import nc.mairie.siale.domain.NoteCritereDataOnDemand;
import nc.mairie.siale.domain.NoteCritereIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NoteCritereIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NoteCritereIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NoteCritereIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NoteCritereIntegrationTest: @Transactional;
    
    @Autowired
    private NoteCritereDataOnDemand NoteCritereIntegrationTest.dod;
    
    @Test
    public void NoteCritereIntegrationTest.testCountNoteCriteres() {
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", dod.getRandomNoteCritere());
        long count = NoteCritere.countNoteCriteres();
        Assert.assertTrue("Counter for 'NoteCritere' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NoteCritereIntegrationTest.testFindNoteCritere() {
        NoteCritere obj = dod.getRandomNoteCritere();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to provide an identifier", id);
        obj = NoteCritere.findNoteCritere(id);
        Assert.assertNotNull("Find method for 'NoteCritere' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'NoteCritere' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NoteCritereIntegrationTest.testFindAllNoteCriteres() {
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", dod.getRandomNoteCritere());
        long count = NoteCritere.countNoteCriteres();
        Assert.assertTrue("Too expensive to perform a find all test for 'NoteCritere', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<NoteCritere> result = NoteCritere.findAllNoteCriteres();
        Assert.assertNotNull("Find all method for 'NoteCritere' illegally returned null", result);
        Assert.assertTrue("Find all method for 'NoteCritere' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NoteCritereIntegrationTest.testFindNoteCritereEntries() {
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", dod.getRandomNoteCritere());
        long count = NoteCritere.countNoteCriteres();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<NoteCritere> result = NoteCritere.findNoteCritereEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'NoteCritere' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'NoteCritere' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NoteCritereIntegrationTest.testFlush() {
        NoteCritere obj = dod.getRandomNoteCritere();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to provide an identifier", id);
        obj = NoteCritere.findNoteCritere(id);
        Assert.assertNotNull("Find method for 'NoteCritere' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNoteCritere(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'NoteCritere' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NoteCritereIntegrationTest.testMergeUpdate() {
        NoteCritere obj = dod.getRandomNoteCritere();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to provide an identifier", id);
        obj = NoteCritere.findNoteCritere(id);
        boolean modified =  dod.modifyNoteCritere(obj);
        Integer currentVersion = obj.getVersion();
        NoteCritere merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'NoteCritere' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NoteCritereIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", dod.getRandomNoteCritere());
        NoteCritere obj = dod.getNewTransientNoteCritere(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'NoteCritere' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'NoteCritere' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NoteCritereIntegrationTest.testRemove() {
        NoteCritere obj = dod.getRandomNoteCritere();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteCritere' failed to provide an identifier", id);
        obj = NoteCritere.findNoteCritere(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'NoteCritere' with identifier '" + id + "'", NoteCritere.findNoteCritere(id));
    }
    
}
