// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.Bareme;
import nc.mairie.siale.domain.BaremeDataOnDemand;
import nc.mairie.siale.domain.NoteGroupe;
import nc.mairie.siale.domain.NoteGroupeDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NoteGroupeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NoteGroupeDataOnDemand: @Component;
    
    private Random NoteGroupeDataOnDemand.rnd = new SecureRandom();
    
    private List<NoteGroupe> NoteGroupeDataOnDemand.data;
    
    @Autowired
    private BaremeDataOnDemand NoteGroupeDataOnDemand.baremeDataOnDemand;
    
    public NoteGroupe NoteGroupeDataOnDemand.getNewTransientNoteGroupe(int index) {
        NoteGroupe obj = new NoteGroupe();
        setBareme(obj, index);
        setNom(obj, index);
        setPonderation(obj, index);
        return obj;
    }
    
    public void NoteGroupeDataOnDemand.setBareme(NoteGroupe obj, int index) {
        Bareme bareme = baremeDataOnDemand.getRandomBareme();
        obj.setBareme(bareme);
    }
    
    public void NoteGroupeDataOnDemand.setNom(NoteGroupe obj, int index) {
        String nom = "nom_" + index;
        obj.setNom(nom);
    }
    
    public void NoteGroupeDataOnDemand.setPonderation(NoteGroupe obj, int index) {
        double ponderation = new Integer(index).doubleValue();
        obj.setPonderation(ponderation);
    }
    
    public NoteGroupe NoteGroupeDataOnDemand.getSpecificNoteGroupe(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NoteGroupe obj = data.get(index);
        Long id = obj.getId();
        return NoteGroupe.findNoteGroupe(id);
    }
    
    public NoteGroupe NoteGroupeDataOnDemand.getRandomNoteGroupe() {
        init();
        NoteGroupe obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NoteGroupe.findNoteGroupe(id);
    }
    
    public boolean NoteGroupeDataOnDemand.modifyNoteGroupe(NoteGroupe obj) {
        return false;
    }
    
    public void NoteGroupeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NoteGroupe.findNoteGroupeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NoteGroupe' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NoteGroupe>();
        for (int i = 0; i < 10; i++) {
            NoteGroupe obj = getNewTransientNoteGroupe(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
