// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.NoteGroupe;
import nc.mairie.siale.domain.NoteGroupeDataOnDemand;
import nc.mairie.siale.domain.NoteGroupeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NoteGroupeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NoteGroupeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NoteGroupeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NoteGroupeIntegrationTest: @Transactional;
    
    @Autowired
    private NoteGroupeDataOnDemand NoteGroupeIntegrationTest.dod;
    
    @Test
    public void NoteGroupeIntegrationTest.testCountNoteGroupes() {
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", dod.getRandomNoteGroupe());
        long count = NoteGroupe.countNoteGroupes();
        Assert.assertTrue("Counter for 'NoteGroupe' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testFindNoteGroupe() {
        NoteGroupe obj = dod.getRandomNoteGroupe();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to provide an identifier", id);
        obj = NoteGroupe.findNoteGroupe(id);
        Assert.assertNotNull("Find method for 'NoteGroupe' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'NoteGroupe' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testFindAllNoteGroupes() {
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", dod.getRandomNoteGroupe());
        long count = NoteGroupe.countNoteGroupes();
        Assert.assertTrue("Too expensive to perform a find all test for 'NoteGroupe', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<NoteGroupe> result = NoteGroupe.findAllNoteGroupes();
        Assert.assertNotNull("Find all method for 'NoteGroupe' illegally returned null", result);
        Assert.assertTrue("Find all method for 'NoteGroupe' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testFindNoteGroupeEntries() {
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", dod.getRandomNoteGroupe());
        long count = NoteGroupe.countNoteGroupes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<NoteGroupe> result = NoteGroupe.findNoteGroupeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'NoteGroupe' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'NoteGroupe' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testFlush() {
        NoteGroupe obj = dod.getRandomNoteGroupe();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to provide an identifier", id);
        obj = NoteGroupe.findNoteGroupe(id);
        Assert.assertNotNull("Find method for 'NoteGroupe' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNoteGroupe(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'NoteGroupe' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testMergeUpdate() {
        NoteGroupe obj = dod.getRandomNoteGroupe();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to provide an identifier", id);
        obj = NoteGroupe.findNoteGroupe(id);
        boolean modified =  dod.modifyNoteGroupe(obj);
        Integer currentVersion = obj.getVersion();
        NoteGroupe merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'NoteGroupe' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", dod.getRandomNoteGroupe());
        NoteGroupe obj = dod.getNewTransientNoteGroupe(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'NoteGroupe' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'NoteGroupe' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NoteGroupeIntegrationTest.testRemove() {
        NoteGroupe obj = dod.getRandomNoteGroupe();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NoteGroupe' failed to provide an identifier", id);
        obj = NoteGroupe.findNoteGroupe(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'NoteGroupe' with identifier '" + id + "'", NoteGroupe.findNoteGroupe(id));
    }
    
}
