// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import nc.mairie.siale.domain.ParamIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParamIntegrationTest_Roo_Configurable {
    
    declare @type: ParamIntegrationTest: @Configurable;
    
}
