// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.Param;
import nc.mairie.siale.domain.ParamDataOnDemand;
import nc.mairie.siale.domain.ParamIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParamIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParamIntegrationTest: @Transactional;
    
    @Autowired
    private ParamDataOnDemand ParamIntegrationTest.dod;
    
    @Test
    public void ParamIntegrationTest.testCountParams() {
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = Param.countParams();
        Assert.assertTrue("Counter for 'Param' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParamIntegrationTest.testFindParam() {
        Param obj = dod.getRandomParam();
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = Param.findParam(id);
        Assert.assertNotNull("Find method for 'Param' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Param' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParamIntegrationTest.testFindAllParams() {
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = Param.countParams();
        Assert.assertTrue("Too expensive to perform a find all test for 'Param', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Param> result = Param.findAllParams();
        Assert.assertNotNull("Find all method for 'Param' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Param' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParamIntegrationTest.testFindParamEntries() {
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = Param.countParams();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Param> result = Param.findParamEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Param' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Param' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParamIntegrationTest.testFlush() {
        Param obj = dod.getRandomParam();
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = Param.findParam(id);
        Assert.assertNotNull("Find method for 'Param' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParam(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Param' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParamIntegrationTest.testMergeUpdate() {
        Param obj = dod.getRandomParam();
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = Param.findParam(id);
        boolean modified =  dod.modifyParam(obj);
        Integer currentVersion = obj.getVersion();
        Param merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Param' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParamIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        Param obj = dod.getNewTransientParam(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Param' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Param' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Param' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParamIntegrationTest.testRemove() {
        Param obj = dod.getRandomParam();
        Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = Param.findParam(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Param' with identifier '" + id + "'", Param.findParam(id));
    }
    
}
