// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.util.List;
import nc.mairie.siale.domain.TypeParam;
import nc.mairie.siale.domain.TypeParamDataOnDemand;
import nc.mairie.siale.domain.TypeParamIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TypeParamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TypeParamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TypeParamIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TypeParamIntegrationTest: @Transactional;
    
    @Autowired
    private TypeParamDataOnDemand TypeParamIntegrationTest.dod;
    
    @Test
    public void TypeParamIntegrationTest.testCountTypeParams() {
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", dod.getRandomTypeParam());
        long count = TypeParam.countTypeParams();
        Assert.assertTrue("Counter for 'TypeParam' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TypeParamIntegrationTest.testFindTypeParam() {
        TypeParam obj = dod.getRandomTypeParam();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to provide an identifier", id);
        obj = TypeParam.findTypeParam(id);
        Assert.assertNotNull("Find method for 'TypeParam' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TypeParam' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TypeParamIntegrationTest.testFindAllTypeParams() {
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", dod.getRandomTypeParam());
        long count = TypeParam.countTypeParams();
        Assert.assertTrue("Too expensive to perform a find all test for 'TypeParam', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TypeParam> result = TypeParam.findAllTypeParams();
        Assert.assertNotNull("Find all method for 'TypeParam' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TypeParam' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TypeParamIntegrationTest.testFindTypeParamEntries() {
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", dod.getRandomTypeParam());
        long count = TypeParam.countTypeParams();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TypeParam> result = TypeParam.findTypeParamEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TypeParam' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TypeParam' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TypeParamIntegrationTest.testFlush() {
        TypeParam obj = dod.getRandomTypeParam();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to provide an identifier", id);
        obj = TypeParam.findTypeParam(id);
        Assert.assertNotNull("Find method for 'TypeParam' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTypeParam(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TypeParam' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeParamIntegrationTest.testMergeUpdate() {
        TypeParam obj = dod.getRandomTypeParam();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to provide an identifier", id);
        obj = TypeParam.findTypeParam(id);
        boolean modified =  dod.modifyTypeParam(obj);
        Integer currentVersion = obj.getVersion();
        TypeParam merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TypeParam' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeParamIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", dod.getRandomTypeParam());
        TypeParam obj = dod.getNewTransientTypeParam(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TypeParam' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TypeParam' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TypeParamIntegrationTest.testRemove() {
        TypeParam obj = dod.getRandomTypeParam();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeParam' failed to provide an identifier", id);
        obj = TypeParam.findTypeParam(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TypeParam' with identifier '" + id + "'", TypeParam.findTypeParam(id));
    }
    
}
