// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nc.mairie.siale.domain.TypeParam;
import nc.mairie.siale.domain.TypeParamDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect TypeParamDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TypeParamDataOnDemand: @Component;
    
    private Random TypeParamDataOnDemand.rnd = new SecureRandom();
    
    private List<TypeParam> TypeParamDataOnDemand.data;
    
    public TypeParam TypeParamDataOnDemand.getNewTransientTypeParam(int index) {
        TypeParam obj = new TypeParam();
        setNom(obj, index);
        return obj;
    }
    
    public void TypeParamDataOnDemand.setNom(TypeParam obj, int index) {
        String nom = "nom_" + index;
        if (nom.length() > 20) {
            nom = nom.substring(0, 20);
        }
        obj.setNom(nom);
    }
    
    public TypeParam TypeParamDataOnDemand.getSpecificTypeParam(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TypeParam obj = data.get(index);
        Long id = obj.getId();
        return TypeParam.findTypeParam(id);
    }
    
    public TypeParam TypeParamDataOnDemand.getRandomTypeParam() {
        init();
        TypeParam obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TypeParam.findTypeParam(id);
    }
    
    public boolean TypeParamDataOnDemand.modifyTypeParam(TypeParam obj) {
        return false;
    }
    
    public void TypeParamDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TypeParam.findTypeParamEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TypeParam' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TypeParam>();
        for (int i = 0; i < 10; i++) {
            TypeParam obj = getNewTransientTypeParam(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
