// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.mairie.siale.domain;

import nc.mairie.siale.domain.TypeParam;

privileged aspect TypeParam_Roo_JavaBean {
    
    public String TypeParam.getNom() {
        return this.nom;
    }
    
    public void TypeParam.setNom(String nom) {
        this.nom = nom;
    }
    
}
